# Sync apps/relay-engine/internal/version/version.go from the repo root VERSION file.
#
# Usage:
#   .\scripts\dev\sync-version.ps1

$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$versionFile = Join-Path $repoRoot "VERSION"
$goVersionFile = Join-Path $repoRoot "apps\relay-engine\internal\version\version.go"

if (-not (Test-Path $versionFile)) {
    Write-Error "VERSION file not found: $versionFile"
}

$version = (Get-Content $versionFile -Raw).Trim()
if ($version -notmatch '^\d+\.\d+\.\d+$') {
    Write-Error "VERSION must be major.minor.patch (example: 0.1.0). Got: $version"
}

$content = @"
// Code generated by scripts/dev/sync-version.ps1. DO NOT EDIT.

package version

const Version = "$version"

"@

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($goVersionFile, $content, $utf8NoBom)
Write-Host "Synced relay version: $version -> $goVersionFile"
